### ISSUE TITLE
Serialization of closure failed

### ISSUE THREAD

**Issue by noxify** [rinvex/cortex-attributes#21]
Tested with the latest Cortex develop branch + latest develop packages.

STRs:

1. Create a new Attribute via Cortex Adminarea
* Name: TestTextField
* Groupname: groupname
* Collection: no
* Type: Rinvex\Attributes\Models\Text
* Entities: Rinvex\Fort\Contracts\UserContract
* Default: sdasda

2. Open the User Management and choose one user

Expected: Edit form is shown and (if I understood it correctly) I can see the defined attribute as a new custom field

Current: The following error message is shown:
```
Serialization of closure failed: Serialization of closure failed: The file containing the closure, "/home/vagrant/projects/cortex/vendor/jeremeamia/SuperClosure/src/SerializableClosure.php(210) : eval()'d code" did not exist.
```

**Comment by noxify** [comment]
The same error occurs when you browse to the "logs" tab inside the created attribute.

**Comment by noxify** [comment]
Solution:
```
php artisan cache:clear
```

**Comment by noxify** [comment]
But the field was/is not shown in the create/edit form.

I have checked the forms and there is currently no implementation to show the defined custom fields.

**Comment by Omranic** [comment]
- Seems a recent update with `rinvex/cacheable` introduced this issue, pushed a fix now! Hope this fix it https://github.com/rinvex/cacheable/commit/6942c0a2a835d6ba5b6044e8e8f52d0ffaed7a17
- For the custom field implementation, yes it's still not automatic, so it's partially incomplete.
