### ISSUE TITLE
Not all fields are saved/shown

### ISSUE THREAD

**Issue by noxify** [rinvex/cortex-attributes#22]
### Create/Update
I have created an attribute which includes an Order definition.

Expected: The order value will be used after clicking on "Submit"
Current: the order field is empty after clicking on "Submit"

### List
I have defined a default value. In the form the value will be shown and can be updated.

Expected: In the list view, the column "Default" shows the defined default value.
Current: In the list view, the column "Default" shows not the defined default value.

**Comment by Omranic** [comment]
Fixed: 9c8c0054d6910c73b223610b9f2b6a45e7b2040d
